[versions]
androidSvg = "1.4"
androidx-activity-compose = "1.8.1"
androidx-core = "1.13.0-alpha02"
androidx-documentfile = "1.1.0-alpha01"
androidx-preference = "1.2.1"
bugsnag-android = "6.1.0"
bugsnag-android-gradle = "8.1.0"
bugsnag-jvm = "3.7.1"
buildkonfig-gradle = "0.15.0"
compose = "1.6.0-alpha01"
compose-compiler = "1.5.4"
conveyor = "1.6"
darklaf = "3.0.2"
flatlaf = "3.2.5"
fluid = "0.13.0"
google-material = "1.12.0-alpha02"
android-gradle = "8.2.0"
javaObjcBridge = "1.2"
jsoup = "1.16.2"
jsystemthemedetector = "3.8"
korlibs = "4.0.10"
kotlin = "1.9.21"
kotlinx-coroutines = "1.7.3"
kotlinx-serialization = "1.6.2"
ktor = "2.3.7"
moko-resources = "0.23.0"
multiplatform-settings = "1.1.0"
slf4j = "2.0.9"

[libraries]
androidSvg = { module = "com.caverock:androidsvg-aar", version.ref = "androidSvg" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentfile" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
bugsnag-android = { module = "com.bugsnag:bugsnag-android", version.ref = "bugsnag-android" }
bugsnag-android-gradle-plugin = { module = "com.bugsnag:bugsnag-android-gradle-plugin", version.ref = "bugsnag-android-gradle" }
bugsnag-jvm = { module = "com.bugsnag:bugsnag", version.ref = "bugsnag-jvm" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
darklaf-core = { module = "com.github.weisj:darklaf-core", version.ref = "darklaf" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
fluid-country = { module = "io.fluidsonic.country:fluid-country", version.ref = "fluid" }
fluid-i18n = { module = "io.fluidsonic.i18n:fluid-i18n", version.ref = "fluid" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
java-objc-bridge = { module = "ca.weblite:java-objc-bridge", version.ref = "javaObjcBridge" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
jSystemThemeDetector = { module = "com.github.Dansoftowner:jSystemThemeDetector", version.ref = "jsystemthemedetector" }
korlibs-korio = { module = "com.soywiz.korlibs.korio:korio", version.ref = "korlibs" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resources" }
multiplatformSettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatformSettings-noArg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }
slf4j = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
bugsnag-android = { id = "com.bugsnag.android.gradle", version.ref = "bugsnag-android-gradle" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig-gradle" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
moko-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-resources" }
conveyor = { id = "dev.hydraulic.conveyor", version.ref = "conveyor" }
